# Generated by Django 3.2.19 on 2023-07-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
    ]
